#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

stage=0
stop_stage=3

dl_dir=/raid/home/yubo1336/datasets
local_dir=/raid/home/yubo1336/datasets/reazonspeech
data_dir=/raid/home/yubo1336/datasets/icefall/data
split=medium
ngpus=8
nproc_per_gpu=4

# . shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p $data_dir

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

log "dl_dir: $dl_dir"

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare ReazonSpeech manifest"
  if [ ! -e $dl_dir/ReazonSpeech/$split/dataset.jsonl ]; then
    python local/prepare_reazonspeech.py download --target-dir $dl_dir --dataset-dir $local_dir --part $split
  fi
  if [ ! -e $data_dir/manifests/$split/reazonspeech_cuts_train.jsonl.gz ]; then
    python local/prepare_reazonspeech.py prepare --corpus-dir $dl_dir/ReazonSpeech --target-dir $data_dir/manifests --part $split
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Preprocess ReazonSpeech manifest"
  mkdir -p $data_dir/kmeans
  if [ ! -f $data_dir/kmeans/$split/reazonspeech_cuts_train_raw.jsonl.gz ]; then
    python local/preprocess_reazonspeech.py --src-dir $data_dir/manifests --output-dir $data_dir/kmeans --part $split
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Extract SSL target for ReazonSpeech"
  if [ ! -e download/hubert_base_ls960.pt ]; then
    wget https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt -P download
  fi
  if [ ! -e download/hubert_base_ls960_L9_km500.bin ]; then
    wget https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960_L9_km500.bin -P download
  fi
  if [ ! -e $data_dir/kmeans//$split/reazonspeech_cuts_train.jsonl.gz ]; then
    OMP_NUM_THREADS=2 python local/extract_kmeans.py \
      --output-dir $data_dir/kmeans \
      --part $split \
      --model-path download/hubert_base_ls960.pt \
      --kmeans-model-path download/hubert_base_ls960_L9_km500.bin \
      --num-proc $((ngpus * nproc_per_gpu))
  fi
fi
